name: Build and Push Docker image
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Plane Delay AI API image
        uses: docker/build-push-action@v5
        with:
          context: ./ai_api
          file: ./ai_api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/plane_delay_ai_api:latest
            ${{ secrets.DOCKER_USERNAME }}/plane_delay_ai_api:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Build and push Plane Delay Data API image
        uses: docker/build-push-action@v5
        with:
          context: ./data_api
          file: ./data_api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/plane_delay_data_api:latest
            ${{ secrets.DOCKER_USERNAME }}/plane_delay_data_api:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Build and push Plane Delay Front image
        uses: docker/build-push-action@v5
        with:
          context: ./streamlit
          file: ./streamlit/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/plane_delay_streamlit:latest
            ${{ secrets.DOCKER_USERNAME }}/plane_delay_streamlit:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move new cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
